apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: in-cluster-agent-poc-cluster-role
rules:
  # ---
  # Required for cost savings estimation features.
  # ---
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
      - services
      - namespaces
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: in-cluster-agent-poc-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: in-cluster-agent-poc-cluster-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
