apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "altc-chart.name" . }}
rules:
  # ---
  # Required for cost savings estimation features.
  # ---
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
      - services
      - namespaces
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "altc-chart.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "altc-chart.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "altc-chart.serviceAccountName" . }}
    namespace: default
